spring:
  datasource:
    url: ${DB_MICRO_URL}
    username: ${DB_MICRO_USERNAME}
    password: ${DB_MICRO_PWD}
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://eureka1:8200/eureka,http://eureka2:8201/eureka


