server:
  port: 8201

spring:
  application:
    name: 'EUREKA-SERVER-2'

eureka:
  instance:
    hostname: eureka2
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://e1:8200/eureka/
    registry-fetch-interval-seconds: 5
    instance-info-replication-interval-seconds: 5